-- =========================================
-- DATABASE BACKUP AUTOMATION PROJECT
-- Author: Kaan Alp Özdemir
-- Description: Full and differential backup with logging and alert system
-- =========================================
