-- =========================================
-- ETL DATA CLEANING PROJECT
-- Author: Kaan Alp Özdemir
-- Description: Raw data cleaning and transformation process
-- =========================================
